// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ShWAVUY32a61PSjAST5FqLmsG45L4t4',
    appId: '1:334527493596:web:53b97aeabed50e142e4b19',
    messagingSenderId: '334527493596',
    projectId: 'gossy-8c56c',
    authDomain: 'gossy-8c56c.firebaseapp.com',
    storageBucket: 'gossy-8c56c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4qPb_s5CeQuKBrSG13xNBu9tclf4EJSU',
    appId: '1:334527493596:android:8f5a416da3d83a4d2e4b19',
    messagingSenderId: '334527493596',
    projectId: 'gossy-8c56c',
    storageBucket: 'gossy-8c56c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy9P041UvWm63pPxUKCHb8pd7ilfCvfQw',
    appId: '1:334527493596:ios:d9878b6aca955c042e4b19',
    messagingSenderId: '334527493596',
    projectId: 'gossy-8c56c',
    storageBucket: 'gossy-8c56c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy9P041UvWm63pPxUKCHb8pd7ilfCvfQw',
    appId: '1:334527493596:ios:d9878b6aca955c042e4b19',
    messagingSenderId: '334527493596',
    projectId: 'gossy-8c56c',
    storageBucket: 'gossy-8c56c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ShWAVUY32a61PSjAST5FqLmsG45L4t4',
    appId: '1:334527493596:web:e5cebe09695be03a2e4b19',
    messagingSenderId: '334527493596',
    projectId: 'gossy-8c56c',
    authDomain: 'gossy-8c56c.firebaseapp.com',
    storageBucket: 'gossy-8c56c.appspot.com',
  );

}